### ISSUE TITLE
Issue: No account or login hint was passed to the AcquireTokenSilent call during reload

### ISSUE THREAD

**Issue by binhnguyen1984** [Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2#259] opened 2020-01-15 12:04 UTC
I got the above error when reloading my web page that uses Azure AD authentication to call a web api. When the page was first loaded, the user logged in and everything was fine. Then after a while, I reload the page and got the error. To be able to reload the page, I had to clear the browser's cache. So what is the issue here and how to solve it?

**Comment by TiagoBrenck** [comment] 2020-01-15 18:34
The issue is because your MSAL cache got cleared (I bet you might be using InMemory) when you restarted your app. However the cookies in the browser stills alive, so when you reload the page, you get an authenticated session because of the cookies but you did pass through the event `OnAuthorizationCodeReceived` which instantiate MSAL cache.

Solutions for your problem would be using the attribute `AuthorizeForScopes`, [documented here](https://github.com/Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2/tree/master/Microsoft.Identity.Web#web-app-controller), and maybe also storing the cache in the DB.

**Comment by binhnguyen1984** [comment] 2020-01-16 07:15
@TiagoBrenck 
I tried out your suggestion but it still did not work. How can we enforce the web page to re-authenticate the user this case?

**Comment by TiagoBrenck** [comment] 2020-01-17 18:14
@jmprieur @kalyankrishna1 @bgavrilMS could you help answer this one?

**Comment by jmprieur** [comment] 2020-01-19 18:25
This is a duplicate of https://github.com/Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2/issues/240

**Closed** 2020-01-19 18:25 UTC
Labels: answered, duplicate, question
