### ISSUE TITLE
1-WebApp-OIDC/1-1-MyOrg (.NET core 3.1) giving Unable to obtain configuration error while 2.2 sample working properly.

### ISSUE THREAD

**Issue by joel-kriel** [Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2#391] opened 2020-08-11 16:04 UTC
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### The issue was found for the following scenario:

Please add an 'x' for the scenario(s) where you found an issue

1. Web app that signs in users
   1. [x] with a work and school account in your organization: [1-WebApp-OIDC/1-1-MyOrg](../blob/master/1-WebApp-OIDC/1-1-MyOrg)
   1. [ ] with any work and school account: [/1-WebApp-OIDC/1-2-AnyOrg](../blob/master/1-WebApp-OIDC/1-2-AnyOrg)
   1. [ ] with any work or school account or Microsoft personal account: [1-WebApp-OIDC/1-3-AnyOrgOrPersonal](../blob/master/1-WebApp-OIDC/1-3-AnyOrgOrPersonal)
   1. [ ] with users in National or sovereign clouds [1-WebApp-OIDC/1-4-Sovereign](../blob/master/1-WebApp-OIDC/1-4-Sovereign)
   1. [ ] with B2C users [1-WebApp-OIDC/1-5-B2C](../blob/master/1-WebApp-OIDC/1-5-B2C)
1. Web app that calls Microsoft Graph
   1. [ ] Calling graph with the Microsoft Graph SDK: [2-WebApp-graph-user/2-1-Call-MSGraph](../blob/master/2-WebApp-graph-user/2-1-Call-MSGraph)
   1. [ ] With specific token caches: [2-WebApp-graph-user/2-2-TokenCache](../blob/master/2-WebApp-graph-user/2-2-TokenCache)
   1. [ ] Calling Microsoft Graph in national clouds: [2-WebApp-graph-user/2-4-Sovereign-Call-MSGraph](../blob/master/2-WebApp-graph-user/2-4-Sovereign-Call-MSGraph)
1. [ ] Web app calling several APIs [3-WebApp-multi-APIs](../blob/master/3-WebApp-multi-APIs)
1. [ ] Web app calling your own Web API [4-WebApp-your-API](../blob/master/4-WebApp-your-API)
1. Web app restricting users
   1. [ ] by Roles: [5-WebApp-AuthZ/5-1-Roles](../blob/master/5-WebApp-AuthZ/5-1-Roles)
   1. [ ] by Groups: [5-WebApp-AuthZ/5-2-Groups](../blob/master/5-WebApp-AuthZ/5-2-Groups)
1. [ ] Deployment to Azure
1. [ ] Other (please describe)

### Repro-ing the issue

Unable to get the sample code working out of the box for 1-WebApp-OIDC/1-1-MyOrg. I was able to use the 2.2 version out of the box using the same set-up steps. 
https://github.com/Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2/archive/aspnetcore2-2.zip

**Repro steps**

1. Download sample code https://github.com/Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2
2. Modify appsettings.json to my settings replacing [token] values

"AzureAd": {
    "Instance": "https://login.microsoftonline.com/",
    "Domain": "[DOMAIN].onmicrosoft.com",
    "TenantId": "[GUID]", 
    "ClientId": "[GUID]",
    "CallbackPath": "/signin-oidc",
    "SignedOutCallbackPath ": "/signout-callback-oidc"
  }
3. Run application

**Expected behavior**
Application should run and immediately attempts to authenticate you via the identity platform endpoint. Sign in with your personal account or with work or school account.

**Actual behavior**
Application throws an error, here is the console error:
fail: Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware[1]
      An unhandled exception has occurred while executing the request.
System.InvalidOperationException: IDX20803: Unable to obtain configuration from: 'https://login.microsoftonline.com/common/discovery/instance?authorization_endpoint=https://login.microsoftonline.com/common/oauth2/v2.0/authorize&api-version=1.1'.
 ---> System.IO.IOException: IDX20804: Unable to retrieve document from: 'https://login.microsoftonline.com/common/discovery/instance?authorization_endpoint=https://login.microsoftonline.com/common/oauth2/v2.0/authorize&api-version=1.1'.

**Possible Solution**

**Additional context/ Error codes / Screenshots**

Using the sample for 2.2 (https://github.com/Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2/archive/aspnetcore2-2.zip) from the quick start guide (https://docs.microsoft.com/en-us/azure/active-directory/develop/quickstart-v2-aspnet-core-webapp) I was able to successfully authenticate using the exact same setup steps described above. 

### Any log messages given by the failure
Add any other context about the problem here, such as logs. 

- You can enable Middleware diagnostics by uncommenting the following [lines](https://github.com/Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2/blob/418e4880ce3307befb25c7af600a886560cadcaa/Microsoft.Identity.Web/StartupHelpers.cs#L81-L83)
- You can enable personally identifiable information in your exceptions to get more information in the open id connect middleware see [Seeing [PII is hidden] in log messages](https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/wiki/PII) 
- Logging for MSAL.NET is described at [Loggin in MSAL.NET](https://docs.microsoft.com/en-us/azure/active-directory/develop/msal-logging#logging-in-msalnet)

### OS and Version?
> Windows 7, 8 or 10. Linux (which distribution). macOS (Yosemite? El Capitan? Sierra?)
> Windows 10

### Versions
> of ASP.NET Core, of MSAL.NET
> ASP.NET Core 3.1
> Microsoft.Identity.Web.UI 0.2.2-preview
> Microsoft.Identity.Web 0.2.2-preview

### Attempting to troubleshooting yourself:

- did you go through the README.md in the folder where you found the issue?
- did you go through the documentation:
  - [Scenario: Web app that signs in users](https://docs.microsoft.com/en-us/azure/active-directory/develop/scenario-web-app-sign-user-overview)
  - [Scenario: Web app that calls web APIs](https://docs.microsoft.com/en-us/azure/active-directory/develop/scenario-web-app-call-api-overview)
  
### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by Shama-K** [comment] 2020-08-11 17:31
@joel-kriel, I'd run the sample but could not reproduce the issue. Can you share if you have customized code or are there any extra steps taken?

**Comment by joel-kriel** [comment] 2020-08-11 18:13
> @joel-kriel, I'd run the sample but could not reproduce the issue. Can you share if you have customized code or are there any extra steps taken?

The only change I did to startup.cs was the following:

using Microsoft.IdentityModel.Logging;

and then added this in ConfigureServices

IdentityModelEventSource.ShowPII = true;

Beside that, I just updated the appsetting.json file and ran the project. The 2.2 linked here (https://docs.microsoft.com/en-us/azure/active-directory/develop/quickstart-v2-aspnet-core-webapp) works fine for me but the 3.1 in this GIT (https://github.com/Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2) does not. 

My app registration 
![AzureAppRegistration](https://user-images.githubusercontent.com/69523351/89933267-d02b2d00-dbdc-11ea-8cd1-d992eb14a80e.png)

**Comment by Shama-K** [comment] 2020-08-11 21:28
Can you share the configuration file? And also the output when you click below link: 
https://login.microsoftonline.com/common/discovery/instance?authorization_endpoint=https://login.microsoftonline.com/common/oauth2/v2.0/authorize&api-version=1.1

**Comment by jmprieur** [comment] 2020-08-12 07:29
Would you have a proxy? or a firewall preventing you to access the discovery endpoint, @joel-kriel ?

**Comment by joel-kriel** [comment] 2020-08-12 11:51
> Can you share the configuration file? And also the output when you click below link:
> https://login.microsoftonline.com/common/discovery/instance?authorization_endpoint=https://login.microsoftonline.com/common/oauth2/v2.0/authorize&api-version=1.1

Which configuration file?

This is the output when I click on the link:
{"tenant_discovery_endpoint":"https://login.microsoftonline.com/common/v2.0/.well-known/openid-configuration","api-version":"1.1","metadata":[{"preferred_network":"login.microsoftonline.com","preferred_cache":"login.windows.net","aliases":["login.microsoftonline.com","login.windows.net","login.microsoft.com","sts.windows.net"]},{"preferred_network":"login.partner.microsoftonline.cn","preferred_cache":"login.partner.microsoftonline.cn","aliases":["login.partner.microsoftonline.cn","login.chinacloudapi.cn"]},{"preferred_network":"login.microsoftonline.de","preferred_cache":"login.microsoftonline.de","aliases":["login.microsoftonline.de"]},{"preferred_network":"login.microsoftonline.us","preferred_cache":"login.microsoftonline.us","aliases":["login.microsoftonline.us","login.usgovcloudapi.net"]},{"preferred_network":"login-us.microsoftonline.com","preferred_cache":"login-us.microsoftonline.com","aliases":["login-us.microsoftonline.com"]}]}

**Comment by joel-kriel** [comment] 2020-08-12 11:55
> Would you have a proxy? or a firewall preventing you to access the discovery endpoint, @joel-kriel ?

Yes I am behind a corporate proxy. I was going down this path until I downloaded the 2.2 sample and that worked. I thought it was not the proxy at that point. 

I did modify my devenv.exe.config file here
>C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\Common7\IDE
to this
>    <system.net>
>	<defaultProxy useDefaultCredentials="true" enabled="true">
>    		<proxy bypassonlocal="true" proxyaddress="http://zs-servroxy.xxx.com:80" />
>	</defaultProxy>
>      <settings>
>        <ipv6 enabled="true"/>
>      </settings>
>    </system.net>

**Comment by Shama-K** [comment] 2020-08-14 22:34
Could you run a tool like fiddler and diagnose what might be going wrong with the network calls?
Please also look at the changes between 2.2 and 3.0 [here](https://docs.microsoft.com/en-us/aspnet/core/release-notes/aspnetcore-3.0?view=aspnetcore-3.1),  as one of those changes might be affecting your network scenario.

**Comment by jmprieur** [comment] 2020-11-02 11:08
Closing as there was no answer.
@joel-kriel feel free to reopen if you wish

**Closed by jmprieur** 2020-11-02 11:08 UTC
