### ISSUE TITLE
When will Microsoft.Identity.Web be available as a nuget package?

### ISSUE THREAD

**Issue by udlose** [Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2#242] opened 2019-12-20 22:21 UTC
When will Microsoft.Identity.Web be available as a nuget package?  It is absolutely ridiculous that I have to cobble together pieces of sample code - _that I have to maintain_ - to get this functionality.

**Comment by NikolaosWakem** [comment] 2019-12-27 09:17
netstandard2.1 rather than netcoreapp3.0 ideally please :-D

**Comment by benc-uk** [comment] 2020-01-02 10:38
Went looking for a NuGet package as well, crazy that in 2020 there's still no official library support for v2.0 endpoints in .NET Core! 
Why is this functionally locked away in a _sample_

**Comment by TiagoBrenck** [comment] 2020-01-07 18:38
We understand your frustrations and we also want Microsoft.Identity.Web to be out as a package or something similar. Unfortunately there are still some internal arrangements pending to be solved before Microsoft.Identity.Web moves out from the sample repository. 

The main thread about this topic is being discussed here: https://github.com/Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2/issues/69

**Comment by jmprieur** [comment] 2020-02-09 23:37
Closing as a dupe of #69

**Closed by jmprieur** 2020-02-09 23:37 UTC
