### ISSUE TITLE
Microsoft.CodeDom.Providers.DotNetCompilerPlatform, Version=3.6.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35" could not be located

### ISSUE THREAD

**Issue by mriepe-lab** [Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2#622] opened 2022-10-10 16:09 UTC
The CodeDom provider type "Microsoft.CodeDom.Providers.DotNetCompilerPlatform.CSharpCodeProvider, Microsoft.CodeDom.Providers.DotNetCompilerPlatform, Version=3.6.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35" could not be located. (D:\AppModelv2-WebApp-OpenIDConnect-DotNet-master\AppModelv2-WebApp-OpenIDConnect-DotNet-master\AppModelv2-WebApp-OpenIDConnect-DotNet\web.config line 73

IIS Webconfig:
  <system.codedom>
    <compilers>
	  <compiler extension=".cs" language="c#;cs;csharp" warningLevel="4" compilerOptions="/langversion:7.3 /nowarn:1659;1699;1701;612;618" type="Microsoft.CodeDom.Providers.DotNetCompilerPlatform.CSharpCodeProvider, Microsoft.CodeDom.Providers.DotNetCompilerPlatform, Version=3.6.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35" />
	  <compiler extension=".vb" language="vb;vbs;visualbasic;vbscript" warningLevel="4" compilerOptions="/langversion:default /nowarn:41008,40000,40008 /define:_MYTYPE=\&quot;Web\&quot; /optionInfer+" type="Microsoft.CodeDom.Providers.DotNetCompilerPlatform.VBCodeProvider, Microsoft.CodeDom.Providers.DotNetCompilerPlatform, Version=3.6.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35" />
    </compilers>
  </system.codedom>

**Comment by mriepe-lab** [comment] 2022-10-10 17:32
This is IIS Windows 2012, using Visual Studio 2019

**Comment by v-michaelmi** [comment] 2022-10-14 20:04
It's looking like the issue is you're trying to run a project that's on `net6.0` which isn't supported on VS2019.

Are you able to upgrade to VS2022?

**Comment by v-michaelmi** [comment] 2022-10-21 16:42
Closing this issue.

@mriepe-lab if this didn't resolve your problem, please feel free to re-open.

**Closed by v-michaelmi** 2022-10-21 16:42 UTC
