### ISSUE TITLE
Token Cache remains after logout

### ISSUE THREAD

**Issue by HenningRoigaard** [Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2#130] opened 2019-07-18 14:33 UTC
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### The issue was found for the following scenario:

Please add an 'x' for the scenario(s) where you found an issue

1. [ ] Web app that signs in users
   1. [ ] with a work and school account in your organization: [1-WebApp-OIDC/1-1-MyOrg](../blob/master/1-WebApp-OIDC/1-1-MyOrg)
   1. [ ] with any work and school account: [/1-WebApp-OIDC/1-2-AnyOrg](../blob/master/1-WebApp-OIDC/1-2-AnyOrg)
   1. [ ] with any work or school account or Microsoft personal account: [1-WebApp-OIDC/1-3-AnyOrgOrPersonal](../blob/master/1-WebApp-OIDC/1-3-AnyOrgOrPersonal)
   1. [ ] with users in National or sovereign clouds [1-WebApp-OIDC/1-4-Sovereign](../blob/master/1-WebApp-OIDC/1-4-Sovereign)
   1. [ ] with B2C users [1-WebApp-OIDC/1-5-B2C](../blob/master/1-WebApp-OIDC/1-5-B2C)
1. Web app that calls Microsoft Graph
   1. [x] Calling graph with the Microsoft Graph SDK: [2-WebApp-graph-user/2-1-Call-MSGraph](../blob/master/2-WebApp-graph-user/2-1-Call-MSGraph)
   1. [ ] With specific token caches: [2-WebApp-graph-user/2-2-TokenCache](../blob/master/2-WebApp-graph-user/2-2-TokenCache)
   1. [ ] Calling Microsoft Graph in national clouds: [2-WebApp-graph-user/2-4-Sovereign-Call-MSGraph](../blob/master/2-WebApp-graph-user/2-4-Sovereign-Call-MSGraph)
1. [ ] Web app calling several APIs [3-WebApp-multi-APIs](../blob/master/3-WebApp-multi-APIs)
1. [ ] Web app calling your own Web API
1. Web app restricting users
   1. [ ] by Roles: [5-WebApp-AuthZ/5-1-Roles](../blob/master/5-WebApp-AuthZ/5-1-Roles)
   1. [ ] by Groups: [5-WebApp-AuthZ/5-2-Groups](../blob/master/5-WebApp-AuthZ/5-2-Groups)
1. [ ] Deployment to Azure
1. [ ] Other (please describe)

### Repro-ing the issue

It appears that token caches are never cleared entirely. I have marked this issue as related to 2-1-Call-MSGraph, but the issue is really with the token caches in general (2-1 is just the first using a cache) or perhaps TokenAcquisition.

In TokenAcquisition.RemoveAccount, we invoke 

```
this.UserTokenCacheProvider?.Clear(account.HomeAccountId.Identifier); 
await app.RemoveAsync(account);
```

However, app.RemoveAsync results in UserTokenCacheAfterAccessNotification being invoked with correct AccountId but an almost empty token cache, resulting in the token cache being persisted again with a useless token!?

**Repro steps**

Simply run 2-1 with breakpoint in Clear and UserTokenCacheAfterAccessNotification, and then log out.

**Expected behavior**
Tokens are deleted on logout

**Actual behavior**
(nearly) Empty token remains

**Possible Solution**
I believe the two method should be invoked in reverse order, or we need some way to identify these "empty" tokens in the cache providers, so that we can avoid persisting them.

**Comment by TiagoBrenck** [comment] 2019-07-22 17:24
@HenningRoigaard it was actually a bug when using guest accounts. The fix got merged already.

Thanks

**Comment by HenningRoigaard** [comment] 2019-07-23 06:56
I am aware of the Guest user issue , and this is something else. Fix issue 130 does not fix this.

This issue can be reproduced with fix 130, both for guest and regular accounts. The issue remains that UserTokenCacheAfterAccessNotification is invoked after cache is cleared, with a dirty (args.HasStateChanged) but empty cache. The code as is, persists that empty cache, and as a result, we will accumulate accountids.

**Comment by TiagoBrenck** [comment] 2019-07-23 17:27
@HenningRoigaard I used this sample, https://github.com/Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2/tree/master/2-WebApp-graph-user/2-2-TokenCache, to test and after logging out, I had an empty table on the DB. 

So, could you please tell me how did you get this empty cache persisted?

**Comment by HenningRoigaard** [comment] 2019-07-24 07:47
I have tested using 2-2, and you are correct: there is no entry in the database after logout. However, this is due to some lucky but most likely unintentional programming :)
The flow from the point of view of **MSALPerUserSqlTokenCacheProvider** when signing out is:
1.	Create instance of **MSALPerUserSqlTokenCacheProvider**
2.	Invoke **UserTokenCacheBeforeAccessNotification**, which invokes **ReadCacheForSignedInUser**, and thus initializes **InMemoryCache** with my credentials
3.	Invoke Clear, which deletes from database but leaves **InMemoryCache** initialized with my credentials
4.	Invoke **UserTokenCacheAfterAccessNotification** with empty cache (as described previously). 

This is where the luck part comes in: Because the same instance is used for both **Clear** and subsequent **UserTokenCacheAfterAccessNotification** (it’s the same “scope”), the **InMemoryCache** remains initialized, and we then try to persist the empty token as an update. As it does not exist, this result in and [DbUpdateConcurrencyException](https://github.com/Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2/files/3425465/exception.txt), which we catch and ignore. 

Clearing **InMemoryCache** as part of **Clear** will not solve the problem. It will simply result in us persisting an empty cache.

**Comment by TiagoBrenck** [comment] 2019-07-26 00:17
After investigating it further more with the engineering team, we could reproduce what you pointed out but this behavior is actually by design. So, when you clear the cache, MSAL doesn't exclude the entry but saves an empty JSON of the cache entry. 
The bytes that you are seeing when inspecting the memory cache is this JSON:

```
"{\"AccessToken\":{},\"RefreshToken\":{},\"IdToken\":{},\"Account\":{},\"AppMetadata\":{\"appmetadata-login.windows.net-{GUID}\":{\"environment\":\"login.windows.net\",\"client_id\":\"{GUID}\"}}}"
```

So, the access token, refresh token and id token are being cleared properly and there is no "random garbage" being saved. It is just the empty JSON of the token entry class.

I hope it answers your question. 
Thanks for pointing that out though.

**Comment by HenningRoigaard** [comment] 2019-07-26 06:48
@TiagoBrenck I can accept that MSAL callbacks with an empty cache by design. 

However, I still believe it would be a good idea to do cleanup of empty caches, e.g., by not persisting them in the first place. From a storage perspective, it probably doesn't matter. However, I fear that accumulation might result in some GDPR compliance issue, and more generally, I would like to do it simply because of best practice housekeeping/cleanup.

If TokenAcquisition.RemoveAccount remains inchanged, it will be the responsibility of a custom cacheprovider to identify and avoid persisting empty caches if so desired. 

1. What is a good criteria for identifying an empty cache in UserTokenCacheAfterAccessNotification? The ITokenCache s not null, and it doesn't have an "IsEmpty" property or anything like it...

Alternatively, it could be handled centrally in TokenAcquisition.RemoveAccount, by changing the order of Clear and RemoveAsync, so that we can freely persist the empty token only to delete it in Clear.

2. Would that have any unwanted sideeffects?

**Comment by jmprieur** [comment] 2019-07-26 13:51
@TiagoBrenck, please open an issue on MSAL.NET so that the persistance callback help this scenario. We would not want to pass null for public client applications, as Mark explained in the private thread. I like the IsEmpty property on the Token cache serialization argument.

cc: @MarkZuber

**Closed** 2020-02-09 23:45 UTC
Labels: answered, by design
