### ISSUE TITLE
Hybrid clients for protected WebApi

### ISSUE THREAD

**Issue by sameer-kumar** [Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2#444] opened 2020-12-09 23:47 UTC
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ ] feature request
- [x] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### The issue was found for the following scenario:

Please add an 'x' for the scenario(s) where you found an issue

1. Web app that signs in users
   1. [x] with a work and school account in your organization: [1-WebApp-OIDC/1-1-MyOrg](../blob/master/1-WebApp-OIDC/1-1-MyOrg)
   1. [ ] with any work and school account: [/1-WebApp-OIDC/1-2-AnyOrg](../blob/master/1-WebApp-OIDC/1-2-AnyOrg)
   1. [ ] with any work or school account or Microsoft personal account: [1-WebApp-OIDC/1-3-AnyOrgOrPersonal](../blob/master/1-WebApp-OIDC/1-3-AnyOrgOrPersonal)
   1. [ ] with users in National or sovereign clouds [1-WebApp-OIDC/1-4-Sovereign](../blob/master/1-WebApp-OIDC/1-4-Sovereign)
   1. [ ] with B2C users [1-WebApp-OIDC/1-5-B2C](../blob/master/1-WebApp-OIDC/1-5-B2C)
1. Web app that calls Microsoft Graph
   1. [x] Calling graph with the Microsoft Graph SDK: [2-WebApp-graph-user/2-1-Call-MSGraph](../blob/master/2-WebApp-graph-user/2-1-Call-MSGraph)
   1. [ ] With specific token caches: [2-WebApp-graph-user/2-2-TokenCache](../blob/master/2-WebApp-graph-user/2-2-TokenCache)
   1. [ ] Calling Microsoft Graph in national clouds: [2-WebApp-graph-user/2-4-Sovereign-Call-MSGraph](../blob/master/2-WebApp-graph-user/2-4-Sovereign-Call-MSGraph)
1. [ ] Web app calling several APIs [3-WebApp-multi-APIs](../blob/master/3-WebApp-multi-APIs)
1. [ ] Web app calling your own Web API
   1. [x] with a work and school account in your organization: [4-WebApp-your-API/4-1-MyOrg](../blob/master/4-WebApp-your-API/4-1-MyOrg)
   1. [ ] with B2C users: [4-WebApp-your-API/4-2-B2C](../blob/master/4-WebApp-your-API/4-2-B2C)
   1. [ ] with any work and school account: [4-WebApp-your-API/4-3-AnyOrg](../blob/master/4-WebApp-your-API/4-3-AnyOrg)
1. Web app restricting users
   1. [ ] by Roles: [5-WebApp-AuthZ/5-1-Roles](../blob/master/5-WebApp-AuthZ/5-1-Roles)
   1. [ ] by Groups: [5-WebApp-AuthZ/5-2-Groups](../blob/master/5-WebApp-AuthZ/5-2-Groups)
1. [ ] Deployment to Azure
1. [ ] Other (please describe)

### Repro-ing the issue

**Repro steps**

I have followed the sample implementation as posted on [github](https://github.com/Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2/tree/master/4-WebApp-your-API/4-1-MyOrg).

However, there is a common use case which is not addressed. What if the same client i.e. AspNetCore web app also has a view with an Ajax call to invoke the protected WebApi? Because, the current sample implementation returns 401 when accessing WebApi from Ajax call.

Is there any sample for this scenario?

**Expected behavior**

**Actual behavior**

**Possible Solution**

**Additional context/ Error codes / Screenshots**

### Any log messages given by the failure
Add any other context about the problem here, such as logs. 

- You can enable Middleware diagnostics by uncommenting the following [lines](https://github.com/Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2/blob/418e4880ce3307befb25c7af600a886560cadcaa/Microsoft.Identity.Web/StartupHelpers.cs#L81-L83)
- You can enable personally identifiable information in your exceptions to get more information in the open id connect middleware see [Seeing [PII is hidden] in log messages](https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/wiki/PII) 
- Logging for MSAL.NET is described at [Loggin in MSAL.NET](https://docs.microsoft.com/en-us/azure/active-directory/develop/msal-logging#logging-in-msalnet)

### OS and Version?
> Windows 10. 

### Versions
> ASP.NET Core 3.1

### Attempting to troubleshooting yourself:

- did you go through the README.md in the folder where you found the issue?
- did you go through the documentation:
  - [Scenario: Web app that signs in users](https://docs.microsoft.com/en-us/azure/active-directory/develop/scenario-web-app-sign-user-overview)
  - [Scenario: Web app that calls web APIs](https://docs.microsoft.com/en-us/azure/active-directory/develop/scenario-web-app-call-api-overview)
  
### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by pmaytak** [comment] 2020-12-10 07:07
Hello @sameer-kumar.
We have this [Ajax sample](https://github.com/AzureAD/microsoft-identity-web/tree/master/tests/AjaxCallActionsWithDynamicConsent) that uses Microsoft Identity Web and this [Angular SPA sample](https://github.com/Azure-Samples/ms-identity-javascript-angular-spa-aspnetcore-webapi) that calls a protected web API that might help. Is this what you were looking for?

**Comment by sameer-kumar** [comment] 2020-12-10 16:46
@pmaytak I looked at your [Ajax sample](https://github.com/AzureAD/microsoft-identity-web/tree/master/tests/AjaxCallActionsWithDynamicConsent) but that one invokes internal MVC controller. I need to invoke an external WebApi from Ajax call.

**Comment by jmprieur** [comment] 2020-12-10 17:33
Maybe this sample would be a good start? 
https://github.com/Azure-Samples/ms-identity-javascript-react-spa-dotnetcore-webapi-obo

@derisen: would you have a better suggestion?

**Comment by derisen** [comment] 2020-12-10 22:30
I would recommend these two:

[VanillaJS SPA calling a Node.js web API](https://github.com/Azure-Samples/ms-identity-javascript-tutorial/tree/main/3-Authorization-II/1-call-api)
[Angular SPA calling a .NET Core web API](https://github.com/Azure-Samples/ms-identity-javascript-angular-spa-aspnetcore-webapi)

**Comment by sameer-kumar** [comment] 2020-12-10 23:08
@derisen yes, most of our apps use jQuery/ajax for invoking WebApis hence I want to stick to the standard.

**Comment by derisen** [comment] 2020-12-10 23:32
@sameer-kumar gotcha! I will add a new branch to first one (1), hopefully in the next couple of days. I'll pass the link here once its ready.

**Comment by sameer-kumar** [comment] 2020-12-11 00:28
@derisen cool. let me know for any questions you may have. Thanks!

**Comment by derisen** [comment] 2020-12-11 21:41
@sameer-kumar see here the [sample using XMLHttpRequest for web api calls](https://github.com/Azure-Samples/ms-identity-javascript-tutorial/tree/c3s1-using-ajax/3-Authorization-II/1-call-api) (Its under the `c3s1-using-ajax` branch). Feel free to close the issue if that solves your problem.

**Comment by sameer-kumar** [comment] 2020-12-11 22:39
@derisen This is what I get when I try to sign-in:

> Access to fetch at 'https://login.microsoftonline.com/XX/oauth2/v2.0/token' from origin 'http://localhost:3000' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.

**Comment by derisen** [comment] 2020-12-11 22:57
@sameer-kumar can you confirm that you've followed the registration steps in the [README](https://github.com/Azure-Samples/ms-identity-javascript-tutorial/blob/c3s1-using-ajax/3-Authorization-II/1-call-api/README.md) correctly? If so, can you please share your configuration for both the SPA and the web API projects?

**Comment by sameer-kumar** [comment] 2020-12-11 23:08
@derisen Yes, I have followed the suggested steps and verified them once again after your comment.
I have made changes to following files:
- SPA>App>authConfig.js
  - clientId: "3dc74506-7631-xxxx-xxxx-1f9a4c44a42c",
        authority: "https://login.microsoftonline.com/xxxxxxxx-xxxx-xxxx-b86d-2ba84a24cdc4",
        redirectUri: "http://localhost:3000",
- SPA > App > apiConfig.js
  - uri: "http://localhost:5000/api",
    scopes: ["api://dc474b66-xxxx-xxxx-xxxx-f41f30b3a8d3/access_as_user"] // e.g. ["scp1", "scp2"]
- API > config.json
  - "credentials": {
        "tenantID": "xxxxxxxx-xxxx-xxxx-b86d-2ba84a24cdc4",
        "clientID": "dc474b66-xxxx-xxxx-xxxx-f41f30b3a8d3",
        "audience": "dc474b66-xxxx-xxxx-xxxx-f41f30b3a8d3"
    },

**Comment by derisen** [comment] 2020-12-11 23:18
@sameer-kumar Thanks. That's strange. Can you also confirm that in your application manifest (go to Azure portal > Azure Active Directory > App Registration > "name-of-your-app" > Manifest), you have these values set:

In SPA's manifest:

```JSON
	"replyUrlsWithType": [
		{
			"url": "http://localhost:3000",
			"type": "Spa"
		}
	],
```

In web API's manifest: 

```JSON
	"accessTokenAcceptedVersion": 2,
```

If that's also confirmed, I'm not sure what's the issue here. Please send me (dogan.erisen AT gmail.com) a network trace using something like [Fiddler](https://www.telerik.com/fiddler).

**Comment by sameer-kumar** [comment] 2020-12-11 23:30
@derisen Ensured those entries. Still no luck. Sending you the logs now.. Thanks.

**Comment by sameer-kumar** [comment] 2020-12-11 23:38
@derisen Just realized that can't send over office network. Sorry man.

**Comment by derisen** [comment] 2020-12-12 00:20
@sameer-kumar Aah, might be a network proxy issue then. Can you perhaps check it at home over the weekend? If it's working, then we at least know its about the corporate network

**Comment by sameer-kumar** [comment] 2020-12-14 18:35
@derisen As suggested, I tried to mimic the sample and run it from home. This time I got passed and got to see the consent screen and was able to successfully login. However, when I click Call API, I got different error:

> Access to XMLHttpRequest at 'http://localhost:5000/' from origin 'http://localhost:3000' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: It does not have HTTP ok status

**Comment by derisen** [comment] 2020-12-15 17:47
@sameer-kumar I'm unable to reproduce this. Can you send me a network trace with [Fiddler](https://www.telerik.com/fiddler) from your home setup at least?

**Comment by sameer-kumar** [comment] 2020-12-15 22:13
@derisen sent you the trace. Its pwd protected with your branch name without dashes.

**Comment by sameer-kumar** [comment] 2020-12-16 15:21
I got an email delivery failure for dogan.erisen@gmail.com

**Comment by derisen** [comment] 2020-12-16 16:35
@sameer-kumar that's weird.. -try using v-doeris At microsoft DOT com

**Comment by sameer-kumar** [comment] 2020-12-23 21:45
@derisen thanks much for your help. Its working now. You can mark this resolved/closed.

**Comment by derisen** [comment] 2020-12-23 21:56
@sameer-kumar you're welcome : ) Would be best to clone, I'll keep it there for now but something might change in future.

**Closed by derisen** 2020-12-23 21:56 UTC
Labels: answered, question
