### ISSUE TITLE
Microsoft.AspNetCore.Authentication.AzureAD.UI breaks with dotnet v. 3.0.0-preview9.19424.4

### ISSUE THREAD

**Issue by vRITHNER** [Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2#184] opened 2019-09-09 17:44 UTC
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [ x] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### The issue was found for the following scenario:

Please add an 'x' for the scenario(s) where you found an issue

1. [ x] Web app that signs in users
   1. [ ] with a work and school account in your organization: [1-WebApp-OIDC/1-1-MyOrg](../blob/master/1-WebApp-OIDC/1-1-MyOrg)
   1. [ ] with any work and school account: [/1-WebApp-OIDC/1-2-AnyOrg](../blob/master/1-WebApp-OIDC/1-2-AnyOrg)
   1. [ ] with any work or school account or Microsoft personal account: [1-WebApp-OIDC/1-3-AnyOrgOrPersonal](../blob/master/1-WebApp-OIDC/1-3-AnyOrgOrPersonal)
   1. [ ] with users in National or sovereign clouds [1-WebApp-OIDC/1-4-Sovereign](../blob/master/1-WebApp-OIDC/1-4-Sovereign)
   1. [ ] with B2C users [1-WebApp-OIDC/1-5-B2C](../blob/master/1-WebApp-OIDC/1-5-B2C)
1. Web app that calls Microsoft Graph
   1. [x ] Calling graph with the Microsoft Graph SDK: [2-WebApp-graph-user/2-1-Call-MSGraph](../blob/master/2-WebApp-graph-user/2-1-Call-MSGraph)
   1. [ ] With specific token caches: [2-WebApp-graph-user/2-2-TokenCache](../blob/master/2-WebApp-graph-user/2-2-TokenCache)
   1. [ ] Calling Microsoft Graph in national clouds: [2-WebApp-graph-user/2-4-Sovereign-Call-MSGraph](../blob/master/2-WebApp-graph-user/2-4-Sovereign-Call-MSGraph)
1. [ ] Web app calling several APIs [3-WebApp-multi-APIs](../blob/master/3-WebApp-multi-APIs)
1. [ ] Web app calling your own Web API
1. Web app restricting users
   1. [ ] by Roles: [5-WebApp-AuthZ/5-1-Roles](../blob/master/5-WebApp-AuthZ/5-1-Roles)
   1. [ ] by Groups: [5-WebApp-AuthZ/5-2-Groups](../blob/master/5-WebApp-AuthZ/5-2-Groups)
1. [ ] Deployment to Azure
1. [ ] Other (please describe)

### Repro-ing the issue

**Repro steps**

- Upgrade the project to `netcoreapp3.0 `

- Ugrade the package 

` <PackageReference Include="Microsoft.AspNetCore.Authentication.AzureAD.UI" Version="3.0.0-preview9.19424.4" />`
**Expected behavior**

> Run as with the netcoreapp2.2
 
**Actual behavior**

> Unhandled exception. System.MissingFieldException: Field not found: 'Microsoft.AspNetCore.Authentication.AzureAD.UI.AzureADDefaults.OpenIdScheme'.
>    at Microsoft.Identity.Web.WebAppServiceCollectionExtensions.AddMicrosoftIdentityPlatformAuthentication(IServiceCollection services, IConfiguration configuration, String configSectionName, Boolean subscribeToOpenIdConnectMiddlewareDiagnosticsEvents)

**Possible Solution**

**Additional context/ Error codes / Screenshots**

### Any log messages given by the failure
Add any other context about the problem here, such as logs. 

- You can enable Middleware diagnostics by uncommenting the following [lines](https://github.com/Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2/blob/418e4880ce3307befb25c7af600a886560cadcaa/Microsoft.Identity.Web/StartupHelpers.cs#L81-L83)
- You can enable personally identifiable information in your exceptions to get more information in the open id connect middleware see [Seeing [PII is hidden] in log messages](https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/wiki/PII) 
- Logging for MSAL.NET is described at [Loggin in MSAL.NET](https://docs.microsoft.com/en-us/azure/active-directory/develop/msal-logging#logging-in-msalnet)

### OS and Version?
> Windows 10 insider preview latest version

### Versions
> of ASP.NET Core, of MSAL.NET

> 3.0.0-preview9.19424.4

### Attempting to troubleshooting yourself:

- did you go through the README.md in the folder where you found the issue?
- did you go through the documentation:
  - [Scenario: Web app that signs in users](https://docs.microsoft.com/en-us/azure/active-directory/develop/scenario-web-app-sign-user-overview)
  - [Scenario: Web app that calls web APIs](https://docs.microsoft.com/en-us/azure/active-directory/develop/scenario-web-app-call-api-overview)
  
### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by jmprieur** [comment] 2019-09-09 23:54
Duplicate of https://github.com/Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2/issues/175

**Comment by jmprieur** [comment] 2019-09-09 23:54
Thanks for your feedback @vRITHNER 
We have not yet ported this sample to ASP.NET Core 3.x

**Comment by wdhodges** [comment] 2019-11-09 09:50
I can say that even running the sample, following the readme on the page doesn't work either. Gives me the following error:
```
Microsoft.AspNetCore.Razor.Design.CodeGeneration.targets(131, 5): rzc generate exited with code -2147450730.
```
I do have dotnet 3.0.x installed, full production. Any ideas on that or just have to wait?

Export of `--info`
![image](https://user-images.githubusercontent.com/11448029/68526637-367ccb00-02ac-11ea-9118-9b891992881c.png)

Thanks!

**Comment by jmprieur** [comment] 2019-11-09 10:56
I'm working on it, @wdhodges

**Comment by wdhodges** [comment] 2019-11-09 11:10
That’s amazing news to hear!

**Comment by TiagoBrenck** [comment] 2020-01-28 20:42
The samples got updated to use Core 3.1.0

**Closed by TiagoBrenck** 2020-01-28 20:42 UTC
Labels: duplicate
