### ISSUE TITLE
NuGet package for Microsoft.Identity.Web

### ISSUE THREAD

**Issue by khenzar** [Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2#69] opened 2019-03-25 12:17 UTC
This is more of a suggestion. I'm pretty sure I'm not the only one who would appreciate if the reusable library project Microsoft.Identity.Web was available as a NuGet package.
That way we can easily keep up with any updates/fixes that you do!
Thank you for considering this!

**Comment by jmprieur** [comment] 2019-04-04 08:42
Thanks for suggesting it.
@khenzar : we are working on it (See https://github.com/AzureAD/microsoft-authentication-extensions-for-dotnet/tree/master/src/Microsoft.Identity.Client.Extensions.Web)

**Comment by RobCannon** [comment] 2019-05-13 01:05
Just trying to get the status of this.  The referenced PR was merged.  But I don't see a NuGet library yet.  Is it under a different name?

**Comment by deckerbd** [comment] 2019-05-14 17:05
@RobCannon I don't believe it's published yet but I could be wrong. I know the latest code in the referenced repo requires the next patch version of the SDK which isn't compatible with VS 2017, nor VS for Mac yet (See https://github.com/AzureAD/microsoft-authentication-extensions-for-dotnet/blob/master/global.json).

Currently the Web extension project isn't targeting .NET Standard 2.0 for the Microsoft.Identity.Client.Extensions.Web package. I forked the other repo and pointed it to netstandard2.0 for now and that's what I'm using locally until it's released on NuGet.

**Comment by jmprieur** [comment] 2019-05-20 10:06
It's not yet published, indeed. But we plan to do so soon
cc: @henrik-me @MarkZuber

**Comment by jackhyder** [comment] 2019-06-26 16:27
Is there an ETA on when this will be available for .NET Core 2?

**Comment by jackpanetta** [comment] 2019-08-20 16:25
Also wondering when this will be available?

Was supposed to be published "soon" on May 20th.

**Comment by TiagoBrenck** [comment] 2019-08-20 20:59
@jackpanetta we don't have an official date yet, but I can tell that this task is still active and there are people working on it.

**Comment by jmprieur** [comment] 2019-08-27 10:13
PR in progress https://github.com/Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2/pull/153

**Comment by okpedersen** [comment] 2019-09-30 09:34
@jmprieur It see that #153 is merged now. But I can't find an official release of the package in the NuGet gallery. When will the package be uploaded?

**Comment by jmprieur** [comment] 2019-10-02 18:39
@SaeedAkhter-MSFT FYI
cc: @henrik-me

**Comment by conkman** [comment] 2019-10-08 03:56
@jmprieur I am also interested in a nuget package for the Microsoft.Identity.Web library.  Do you have an eta for when it will be available?  Thank you in advance.

**Comment by AlphaCreative-Mike** [comment] 2019-10-15 13:34
Any updates on this?  We have several solutions referencing different versions of the source project that we want to sync.  We'd rather use the NuGet package than reference the source project.

**Comment by jmprieur** [comment] 2019-10-16 09:30
No update, yet, @AlphaCreative-Mike 
We are still dicussing how to do that, as this is a bit of a special case: not really a product (we are thinking of a bigger strategy), but at the same time not quite a sample.

**Comment by AlphaCreativeDev** [comment] 2019-10-16 12:45
@jmprieur  - That makes sense.  For anyone who is looking for options, we will probably fork the samples repo and then publish a build of Microsoft.Identity.Web into our private NuGet Repository.  One thing that would make this option better is if Microsoft.Identity.Web was in it's own repo instead of inside the Azure-Samples repo.  I hope this helps others.

**Comment by AlphaCreative-Mike** [comment] 2019-10-16 12:45
@jmprieur  - That makes sense.  For anyone who is looking for options, we will probably fork the samples repo and then publish a build of Microsoft.Identity.Web into our private NuGet Repository.  One thing that would make this option better is if Microsoft.Identity.Web was in it's own repo instead of inside the Azure-Samples repo.  I hope this helps others.

**Comment by sleeplessninja** [comment] 2019-10-21 13:16
@j

> @AlphaCreative-Mike
> Having Microsoft.Identity.Web in its own repo is coming (still as a sample): [http://github.com/Azure-Samples/microsoft.identity.web](https://github.com/Azure-Samples/microsoft.identity.web)
> 
> But how would you want to consume it in your projects, it it was not a NuGet package?
> 
> * As a git submodule?
> * As a repo sitting side by side with your project?
> * as a folder you'd copy in your project?
> * ?

+1 submodule if not a nuget

**Comment by sleeplessninja** [comment] 2019-10-21 13:16
> @AlphaCreative-Mike
> Having Microsoft.Identity.Web in its own repo is coming (still as a sample): [http://github.com/Azure-Samples/microsoft.identity.web](https://github.com/Azure-Samples/microsoft.identity.web)
> 
> But how would you want to consume it in your projects, it it was not a NuGet package?
> 
> * As a git submodule?
> * As a repo sitting side by side with your project?
> * as a folder you'd copy in your project?
> * ?
+1 submodule if not a nuget

**Comment by udlose** [comment] 2019-10-21 22:07
I'd like to see it distributed as a Nuget package. I certainly do not want to maintain a copy of the code if it were in a repo side by side with my own project - unless I misunderstood the comment by @henriksen.

**Comment by alan994** [comment] 2019-11-05 10:03
Any updates with this?

**Comment by BeenaCelin** [comment] 2019-11-05 10:27
waiting for Microsoft.Identity.Web nuget package. Please let us know the tendative date of release. 

Thanks.

**Comment by jackpanetta** [comment] 2019-11-05 18:42
Any idea when this will be done?

It's been open since March.

**Comment by ahollandusc** [comment] 2019-11-07 02:51
Microsoft.Identity.Web nuget package please!

**Comment by jmprieur** [comment] 2019-11-07 09:17
@khenzar @RobCannon @deckerbd @jackhyder @jackpanetta @okpedersen @conkman @AlphaCreative-Mike @henriksen @sleeplessninja @udlose @alan994 @BeenaCelin @ahollandusc @udlose @AlphaCreativeDev @AHelper @FeyonaNThylander  @neilha @martincarlsson @blyw @mcortezfc @carlowahlstedt @dtrammer @Josverl @multcomalan @pwang2 @nikolami @ritdaw @richsage @EtiennePeeters 

Thanks for your support, everybody!

I'm sorry that we are so slow on this one. We want to be sure we have the right API, because then if we change it later, we'd break you, which we want to avoid. And we want to provide a high quality secure by default library (and templates) that is going to fullfil needs. However, our team is also working on MSAL.NET (and maintaining ADAL.NET), where we had to priortize some other work (also important), as you might know if you follow our roadmaps.

Meanwhile I've several questions for you:
- Untill we fully productize it (you might have noticed that there are not many tests)  and make it available from NuGet would it be ok to have a -preview NuGet package out of MyGet or GitHub packages?
- Would you like to get on a call with me so that I understand better your scenarios, and we discuss the possible futures of this?
- Do some of you want to contribute?

**Comment by jmprieur** [comment] 2019-11-07 09:18
cc: @SaeedAkhter-MSFT @mvrak @henrik-me @jennyf19 @bgavrilMS @trwalke

**Comment by mcortezfc** [comment] 2019-11-07 19:15
I'm new to all the related technologies for this, so not currently in a position to contribute much.  But I'm working on Web APIs that will be accessed by interactive client & daemon applications, which might need to access other Web APIs all being backed by either my organization's existing Azure AD/ADFS logins or by CAS SAML2 logins.  It looks like the Microsoft.Identity.Web stuff simplifies a lot of this. I would just be happy to have a single centralized copy of the M.I.W. code base, as currently it looks like there's many copies of that code across several different samples and they're not all in sync.  Getting them into that new repository and relatively bug free using the dotnet core 3.x would be a great/awesome first step. A preview package would be icing on that cake.

**Comment by ahollandusc** [comment] 2019-11-07 22:24
Thanks for the quick reply @jmprieur,
A single centralised preview version (or even beta) nuget package would be awesome. Referencing it from your samples would focus usage and assist end user feedback.
I'm mostly a front end developer trying to do some back end work to secure our API's but happy to contribute where possible.

**Comment by udlose** [comment] 2019-11-08 00:33
@jmprieur what is going to be the difference between `Microsoft.Identity.Client.Extensions.Web` and `Microsoft.Identity.Web`?  The documenation uses them interchangeably and TBH it is quite confusing and unclear. I encourage your team to consider cleaning up the documentation and references to each to be more clear.

**Comment by jmprieur** [comment] 2019-11-08 07:28
You're right we need to clean-up this. There were hesitations, and this is really not clear. thanks for the heads-up @udlose

**Comment by WalternativE** [comment] 2019-11-19 13:02
> Untill we fully productize it (you might have noticed that there are not many tests) and make it available from NuGet would it be ok to have a -preview NuGet package out of MyGet or GitHub packages?

Totally! Far better than the current solution of "copying the project and manually updating it every now and then" 🙈

> Would you like to get on a call with me so that I understand better your scenarios, and we discuss the possible futures of this?

Sure, if that would help you I'd be more than happy to talk with you about our use case.

> Do some of you want to contribute?

Would be in my free-time as I currently can't rationalize the resource usage at work (too many other high priority tasks) but I'm always happy to do some grunt work 🙂

**Comment by BeenaCelin** [comment] 2019-12-10 11:43
@MS team, would you be updating about Microsoft.Identity.Web release information, this will be great help for us before Holidays for our Assets release. Thanks.

**Comment by jmprieur** [comment] 2019-12-11 00:27
@BeenaCelin 
we are currently discussing on how best split this between Microsoft.IdentityExtension for .NET, and ASP.NET Core ..

**Comment by freemstr** [comment] 2019-12-19 17:53
Is Azure B2C token cache compatibility being considered for this release?

**Comment by bgavrilMS** [comment] 2019-12-19 18:21
@freemstr - B2C can be used for public clients as well as in web scenarios and the token cache is compatible. Do you have any problems with it? If so, consider logging a separate issue.

**Comment by freemstr** [comment] 2019-12-20 14:26
@bgavrilMS THank you for clarification
https://github.com/Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2/pull/153#issuecomment-527411746
Which refers to
https://github.com/Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2/pull/153#pullrequestreview-274472461
and also 
https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/wiki/AAD-B2C-specifics#known-issue-with-azure-b2c

I have core 3.1 web front ends and APIs all behind b2c auth
I was waiting for Microsoft.Identity.Web nuget to evaluate migrating from my own token acquisition and caching implementation to Microsoft.Identity.Web, but the above comments suggested it may not work for this purpose.

Unless I am reading this incorrectly
https://github.com/Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2/blob/master/Microsoft.Identity.Web/TokenAcquisition.cs
would contain something along the lines of
https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/wiki/AAD-B2C-specifics#acquiring-a-token-to-apply-a-policy

for this to work in my scenario

**Comment by bgavrilMS** [comment] 2019-12-20 14:30
@freemstr - yes, you right, I understood the wrong message. The token cache schema is the same for AAD, ADFS and B2C, but some assumptions need to be made to account for B2C's use of `policies`. These assumptions are sadly exposed to the developers, and require a lot of inside knowledge to get right.

**Comment by freemstr** [comment] 2019-12-20 21:38
@bgavrilMS this must be why there is still no official guide on JWT Bearer to B2C API from MVC
https://github.com/aspnet/AspNetCore.Docs/issues/13215, which is not solved but merged into
https://github.com/aspnet/AspNetCore.Docs/issues/16186 which is also not closed

Even though its definitely possible with MSAL and has been running in production since core 2.0 release. 

The original delivery date on the above was sometime last week, so maybe there will be something coming in January, fingers crossed.

**Comment by ahelwer** [comment] 2020-01-06 23:05
Is there any update on this? We've been waiting for this package for a very long time...

**Comment by gitjosephbeer** [comment] 2020-01-07 07:33
I'd be intrested on any update concerning a Microsoft.Identity.Web nuGet library as well...

**Comment by sujayvsarma** [comment] 2020-01-08 06:39
I had no idea that such a thing existed until @jmprieur linked me to this repo on another issue elsewhere (See: https://github.com/dotnet/aspnetcore/issues/18117#issuecomment-571744304). 

While you discuss Microsoft.Identity.Web, do bear in mind the following:

- There are way too many packages out there that seem to do the same thing. MSAL, ADAL, Microsoft.Identity.Client.Extensions.Web, and various variants of each library (like B2C, national clouds, private clouds, and Stack). This is confusing not just for us, but even for the teams that maintain the official documentation [as noted in this comment above: https://github.com/Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2/issues/69#issuecomment-551330290]. 

- One of the success factors of Microsoft.Identity.Web should be that it places its USP clearly. When/why/how should this be used? If possible, retire/obsolete everything else in existence at this time in favour or Microsoft.Identity.Web. Like .NET/Fx/Core -> .NET 5. Just one face going forward. This is important.

**My votes for packaged versus submodules and reasoning:**

I would vote for a **package**. This is for the following reasons:

1. Building a package requires that it go through specific quality checks and testing before it is considered releasable. While this means that new features and bug fixes may take longer, the other advantages outweigh the need for speed.

People with highly specific scenarios or need for specific changes to functionality or specific problems fixed can in any case fork the repo and have a local build till the package catches up. Advanced users _will_ do this by default anyway.

2. Having a fork and building projects off it also means that a design by the library's dev team impacts everyone that has forked it, **immediately**. An example is the renaming of the MsalUri… attribute rename that seems to have caused quite some confusion already. Having a package means that it becomes a conscious and deliberate change. You call it out in a RelNotes and then people see that and adjust their code -- when you fork, you don't always find out about breaking changes until build breaks -- if you have an automated CI pipeline all the way to production, you may not find out until you get an angry customer call at 2AM.

**Comment by udlose** [comment] 2020-02-10 04:34
Any update on this issue?

**Comment by szalapski** [comment] 2020-02-14 15:48
I would like this as a package as well.

**Comment by mylesjj** [comment] 2020-02-17 16:47
Me too

**Comment by jmprieur** [comment] 2020-02-18 03:30
We have created a new repo to host Microsoft.Identity.Web (https://github.com/AzureAD/microsoft-identity-web), and to release it as a NuGet package.

**Comment by udlose** [comment] 2020-02-18 19:14
> We have created a new repo to host Microsoft.Identity.Web (https://github.com/AzureAD/microsoft-identity-web). Work is in progress to release it as a NuGet package. The relevant issues were moved there.
> 
> Thanks for your support!

@jmprieur any SWAG on when it will be released as a nuget?

**Comment by jennyf19** [comment] 2020-02-19 18:20
@udlose you can track the progress [here](https://github.com/AzureAD/microsoft-identity-web/projects/2)

**Comment by isaacOjeda** [comment] 2020-02-25 18:20
I don't like this, i spend some time trying to figure out what is happening in all the demos at the docs (like this code sample https://docs.microsoft.com/en-us/azure/active-directory/develop/scenario-web-app-call-api-call-api?tabs=aspnetcore) and then i found the github repo and i have this surprice that i can't get the NuGet package 😣

**Comment by mpp** [comment] 2020-02-26 19:44
Hi! I'm using the separated microsoft-identity-web repository with success with an API application. I need it also for an APP, but when I try to login/logout it doesn't find the Account controller. Do I need to import the microsoft-identity-web-ui project as well? Does it have its own repository or it comes only with this samples collection?

**Comment by jmprieur** [comment] 2020-02-26 20:03
Yes, @mpp, you need to use microsoft-identity-web-ui. It's in the same repo as microsoft.identity.web

**Comment by mpp** [comment] 2020-02-26 20:04
Thanks @jmprieur. I'm dumb, I didn't see it.

**Comment by mohan810** [comment] 2020-03-20 01:56
Is there any update.. its been almost 1 year since the issue is raised. It will be great if this can be a nuget package.

**Comment by jmprieur** [comment] 2020-03-20 02:01
We are working on it. See https://github.com/AzureAD/microsof-identity-web

**Comment by rosdi** [comment] 2020-03-23 13:35
This is awesome, will clone this project since nuget package isn't ready yet. Thanks!

**Comment by jmprieur** [comment] 2020-03-23 16:00
you can generate a NuGet package for yourself, BTW (msbuild /t:pack)
But mind you that's an alpha version, we'll probably still change things in the public API

**Comment by ahelwer** [comment] 2020-04-09 02:10
While we're waiting for a nuget package, where can I find a code sample that *doesn't* use microsoft.identity.web for authentication with kestrel?

**Comment by jmprieur** [comment] 2020-04-09 02:12
@ahelwer : we intend to release a first nuget package in the next couple of days ...
cc: @jennyf19 @pmaytak 
cc: @henrik-me

**Comment by mrjoe882** [comment] 2020-04-12 12:14
When nuget package will be released?

**Comment by jennyf19** [comment] 2020-04-14 04:05
@mrjoe882 It was released earlier today. We are in the process of updating samples.
[Microsoft Identity Web](https://www.nuget.org/packages/Microsoft.Identity.Web/0.1.0-preview)
[Microsoft Identity Web UI](https://www.nuget.org/packages/Microsoft.Identity.Web.UI/0.1.0-preview)
cc: @jmprieur

**Comment by serge2112** [comment] 2020-04-17 14:30
I have been trying to add login/logout functionality by adding both packages to my MVC Web App, but when I try to redirect to MicrosoftIdentity/Account/SignOut I get 404 error. Do I need to create the UI components in my project itself? I would have thought they were included in Microsoft Identity Web UI. I would appreciate some guidance on this.

Sorry if this is the wrong place to post this question. Thanks in advance.

**Comment by TiagoBrenck** [comment] 2020-04-17 16:35
Hi @serge2112,

Make sure you have the package Microsoft.Identity.Web.UI and this configuration:

```
            services.AddControllersWithViews(options =>
            {
                var policy = new AuthorizationPolicyBuilder()
                    .RequireAuthenticatedUser()
                    .Build();
                options.Filters.Add(new AuthorizeFilter(policy));
            }).AddMicrosoftIdentityUI();
```

**Comment by serge2112** [comment] 2020-04-20 19:16
@TiagoBrenck thanks a lot! That solved the issue and allowed me to sign in and out when testing my application locally. 

However, after I deployed the app to an app service on azure, I got "The page cannot be displayed because an internal server error has occurred." while redirecting to /signin-oidc. If I refresh the same page then I get: "Exception: OpenIdConnectAuthenticationHandler: message.State is null or empty."

**Comment by TiagoBrenck** [comment] 2020-04-20 20:09
@serge2112 would you mind opening a new issue to discuss it there? 
When opening the new issue, please provide repro steps to help us troubleshoot the problem.

**Comment by jmprieur** [comment] 2020-06-03 08:53
Closing this one, as Microsoft.Identity.Web is available as a NuGet package (in preview)
See https://github.com/AzureAD/microsoft-identity-web/wiki

**Closed by jmprieur** 2020-06-03 08:53 UTC
Labels: in progress

**Comment by maheshcm80** [comment] 2020-09-07 07:04
When is original version of Microsoft.Identity.Web been released in nuget.

**Comment by jmprieur** [comment] 2020-09-08 08:52
I don't understand the question, @maheshcm80 
Microsoft.Identity.Web (preview) is available from NuGet.org: https://www.nuget.org/packages/Microsoft.Identity.Web

**Comment by udlose** [comment] 2020-09-09 14:55
@jmprieur I think he meant the Release (non-preview)

**Comment by jennyf19** [comment] 2020-09-09 15:02
@maheshcm80 you can follow the progress in the [repo](https://github.com/AzureAD/microsoft-identity-web/projects/11)

**Comment by maheshcm80** [comment] 2020-09-10 06:19
@jennyf19  Thank you

**Comment by PRAKAS1** [comment] 2020-09-17 13:12
https://www.nuget.org/packages/Microsoft.Identity.Web/

**Comment by jennyf19** [comment] 2020-09-30 20:49
Microsoft Identity Web is out of preview now, version 1.0.0. Thanks for all your support & feedback.
Microsoft.Identity.Web is released in NuGet.org as a set of NuGet packages: 
- [Microsoft.Identity.Web](https://www.nuget.org/packages/Microsoft.Identity.Web) which is the main API. 
- [Microsoft.Identity.Web.UI](https://www.nuget.org/packages/Microsoft.Identity.Web.UI) brings the button to sign-in and sign-out users, as well as handle some B2C experiences and the challenge mechanism enabling the library to automatically handle incremental consent and conditional access. The UI is customizable. 
- [Microsoft.Identity.Web.MicrosoftGraph](https://www.nuget.org/packages/Microsoft.Identity.Web.MicrosoftGraph) exposes the graph SDK for .NET GraphServiceClient so that it’s used in your controllers. 
- [Microsoft.Identity.Web.MicrosoftGraphBeta](https://www.nuget.org/packages/Microsoft.Identity.Web.MicrosoftGraphBeta) exposes the graph SDK beta for .NET (corresponding to the Microsoft Graph Beta endpoint)
